typography_spectrum: 0.515612700022757
color:
  brandStrength: 0.48817239981144667
  lightness: 0.6518681449815631
  saturation: 0.08840129734016955
  rhythmicContrast: 0.9261415174696594
  brandColors:
    - '#3F291B'
    - '#28A933'
    - '#86817E'
    - '#72F281'
    - '#FFFEF9'
layout_spectrum: 0.16187215852551162
author:
  name: Marc Lovegrove
  email: m@marc-lovegrove.co.uk
  url: 'http://www.marc-lovegrove.co.uk'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c2acd5df-62c1-4b86-924d-e1631b044064.jpg
name: MSITE
navigation:
  - name: Projections in the Forest
    id: f062a125-5957-4603-8ed6-4a826049760e
    type: content
  - name: Portraits of Dogs as They Shake Off Water
    id: 53ac5aa9-88f4-4e5f-8ca5-c5c65fe99315
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/41d665ad-b12a-4e50-bc53-38158e3ecb3c.jpg
title: Hello there
description: enjoy or get lost
